# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brand_compose.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'brand_compose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62rand_compose.proto\x12\x11\x63reative_campaign\"\xe4\x01\n\x13\x42randComposeRequest\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x12\n\nvariant_id\x18\x03 \x01(\t\x12\x0e\n\x06locale\x18\x04 \x01(\t\x12\x12\n\ns3_uri_raw\x18\x05 \x01(\t\x12\x13\n\x0blogo_s3_uri\x18\x06 \x01(\t\x12\x15\n\rprimary_color\x18\x07 \x01(\t\x12\x15\n\rlogo_position\x18\x08 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\t \x01(\t\x12\x11\n\ttimestamp\x18\n \x01(\t\"\xa2\x01\n\x10\x42randComposeDone\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x12\n\nvariant_id\x18\x03 \x01(\t\x12\x0e\n\x06locale\x18\x04 \x01(\t\x12\x16\n\x0es3_uri_branded\x18\x05 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brand_compose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BRANDCOMPOSEREQUEST']._serialized_start=43
  _globals['_BRANDCOMPOSEREQUEST']._serialized_end=271
  _globals['_BRANDCOMPOSEDONE']._serialized_start=274
  _globals['_BRANDCOMPOSEDONE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
