# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: campaign_brief.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'campaign_brief.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61mpaign_brief.proto\x12\x11\x63reative_campaign\"\x93\x03\n\rCampaignBrief\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12,\n\x08products\x18\x02 \x03(\x0b\x32\x1a.creative_campaign.Product\x12\x16\n\x0etarget_locales\x18\x03 \x03(\t\x12-\n\x08\x61udience\x18\x04 \x01(\x0b\x32\x1b.creative_campaign.Audience\x12\x35\n\x0clocalization\x18\x05 \x01(\x0b\x32\x1f.creative_campaign.Localization\x12\x31\n\x05\x62rand\x18\x06 \x01(\x0b\x32\".creative_campaign.BrandCompliance\x12\x34\n\tplacement\x18\x07 \x01(\x0b\x32!.creative_campaign.BrandPlacement\x12-\n\x06output\x18\x08 \x01(\x0b\x32\x1d.creative_campaign.OutputSpec\x12\x16\n\x0e\x63orrelation_id\x18\t \x01(\t\x12\x11\n\ttimestamp\x18\n \x01(\t\"8\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"f\n\x08\x41udience\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x10\n\x08\x61udience\x18\x02 \x01(\t\x12\x0f\n\x07\x61ge_min\x18\x03 \x01(\x05\x12\x0f\n\x07\x61ge_max\x18\x04 \x01(\x05\x12\x16\n\x0einterests_text\x18\x05 \x01(\t\"^\n\x0cLocalization\x12\x12\n\nmessage_en\x18\x01 \x01(\t\x12\x12\n\nmessage_de\x18\x02 \x01(\t\x12\x12\n\nmessage_fr\x18\x03 \x01(\t\x12\x12\n\nmessage_it\x18\x04 \x01(\t\"\xbb\x01\n\x0f\x42randCompliance\x12\x15\n\rprimary_color\x18\x01 \x01(\t\x12\x13\n\x0blogo_s3_uri\x18\x02 \x01(\t\x12\x17\n\x0f\x62\x61nned_words_en\x18\x03 \x03(\t\x12\x17\n\x0f\x62\x61nned_words_de\x18\x04 \x03(\t\x12\x17\n\x0f\x62\x61nned_words_fr\x18\x05 \x03(\t\x12\x17\n\x0f\x62\x61nned_words_it\x18\x06 \x03(\t\x12\x18\n\x10legal_guidelines\x18\x07 \x01(\t\"F\n\x0e\x42randPlacement\x12\x15\n\rlogo_position\x18\x01 \x01(\t\x12\x1d\n\x15overlay_text_position\x18\x02 \x01(\t\"F\n\nOutputSpec\x12\x15\n\raspect_ratios\x18\x01 \x03(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x11\n\ts3_prefix\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'campaign_brief_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMPAIGNBRIEF']._serialized_start=44
  _globals['_CAMPAIGNBRIEF']._serialized_end=447
  _globals['_PRODUCT']._serialized_start=449
  _globals['_PRODUCT']._serialized_end=505
  _globals['_AUDIENCE']._serialized_start=507
  _globals['_AUDIENCE']._serialized_end=609
  _globals['_LOCALIZATION']._serialized_start=611
  _globals['_LOCALIZATION']._serialized_end=705
  _globals['_BRANDCOMPLIANCE']._serialized_start=708
  _globals['_BRANDCOMPLIANCE']._serialized_end=895
  _globals['_BRANDPLACEMENT']._serialized_start=897
  _globals['_BRANDPLACEMENT']._serialized_end=967
  _globals['_OUTPUTSPEC']._serialized_start=969
  _globals['_OUTPUTSPEC']._serialized_end=1039
# @@protoc_insertion_point(module_scope)
