# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: context_enrich.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'context_enrich.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ontext_enrich.proto\x12\x11\x63reative_campaign\"\xd9\x01\n\x14\x43ontextEnrichRequest\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x0e\n\x06locale\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t\x12\x10\n\x08\x61udience\x18\x04 \x01(\t\x12\x0f\n\x07\x61ge_min\x18\x05 \x01(\x05\x12\x0f\n\x07\x61ge_max\x18\x06 \x01(\x05\x12\x16\n\x0einterests_text\x18\x07 \x01(\t\x12\x15\n\rproduct_names\x18\x08 \x03(\t\x12\x16\n\x0e\x63orrelation_id\x18\t \x01(\t\x12\x11\n\ttimestamp\x18\n \x01(\t\"\x9a\x01\n\x12\x43ontextEnrichReady\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x0e\n\x06locale\x18\x02 \x01(\t\x12\x34\n\x0c\x63ontext_pack\x18\x03 \x01(\x0b\x32\x1e.creative_campaign.ContextPack\x12\x16\n\x0e\x63orrelation_id\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"\x8e\x01\n\x0b\x43ontextPack\x12\x0e\n\x06locale\x18\x01 \x01(\t\x12\x15\n\rculture_notes\x18\x02 \x01(\t\x12\x0c\n\x04tone\x18\x03 \x01(\t\x12\x0b\n\x03\x64os\x18\x04 \x03(\t\x12\r\n\x05\x64onts\x18\x05 \x03(\t\x12\x14\n\x0c\x62\x61nned_words\x18\x06 \x03(\t\x12\x18\n\x10legal_guidelines\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'context_enrich_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXTENRICHREQUEST']._serialized_start=44
  _globals['_CONTEXTENRICHREQUEST']._serialized_end=261
  _globals['_CONTEXTENRICHREADY']._serialized_start=264
  _globals['_CONTEXTENRICHREADY']._serialized_end=418
  _globals['_CONTEXTPACK']._serialized_start=421
  _globals['_CONTEXTPACK']._serialized_end=563
# @@protoc_insertion_point(module_scope)
