# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: creative_generate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'creative_generate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import context_enrich_pb2 as context__enrich__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63reative_generate.proto\x12\x11\x63reative_campaign\x1a\x14\x63ontext_enrich.proto\"\xb0\x02\n\x17\x43reativeGenerateRequest\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x14\n\x0cproduct_name\x18\x03 \x01(\t\x12\x1b\n\x13product_description\x18\x04 \x01(\t\x12\x0e\n\x06locale\x18\x05 \x01(\t\x12\x34\n\x0c\x63ontext_pack\x18\x06 \x01(\x0b\x32\x1e.creative_campaign.ContextPack\x12\x16\n\x0enum_candidates\x18\x07 \x01(\x05\x12\x0c\n\x04seed\x18\x08 \x01(\x05\x12\x10\n\x08revision\x18\t \x01(\x05\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\n \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x0b \x01(\t\x12\x11\n\ttimestamp\x18\x0c \x01(\t\"\xc7\x01\n\x14\x43reativeGenerateDone\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x0e\n\x06locale\x18\x03 \x01(\t\x12\x10\n\x08revision\x18\x04 \x01(\x05\x12\x39\n\ncandidates\x18\x05 \x03(\x0b\x32%.creative_campaign.GeneratedCandidate\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\"\xa6\x01\n\x12GeneratedCandidate\x12\x12\n\nvariant_id\x18\x01 \x01(\t\x12\x12\n\ns3_uri_raw\x18\x02 \x01(\t\x12\x0c\n\x04seed\x18\x03 \x01(\x05\x12\x13\n\x0bprompt_used\x18\x04 \x01(\t\x12\x15\n\rquality_score\x18\x05 \x01(\x02\x12\x11\n\tcompliant\x18\x06 \x01(\x08\x12\x1b\n\x13\x63ompliance_warnings\x18\x07 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'creative_generate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATIVEGENERATEREQUEST']._serialized_start=69
  _globals['_CREATIVEGENERATEREQUEST']._serialized_end=373
  _globals['_CREATIVEGENERATEDONE']._serialized_start=376
  _globals['_CREATIVEGENERATEDONE']._serialized_end=575
  _globals['_GENERATEDCANDIDATE']._serialized_start=578
  _globals['_GENERATEDCANDIDATE']._serialized_end=744
# @@protoc_insertion_point(module_scope)
