# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: overlay_compose.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'overlay_compose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15overlay_compose.proto\x12\x11\x63reative_campaign\"\xf3\x01\n\x15OverlayComposeRequest\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x12\n\nvariant_id\x18\x03 \x01(\t\x12\x0e\n\x06locale\x18\x04 \x01(\t\x12\x16\n\x0es3_uri_branded\x18\x05 \x01(\t\x12\x0c\n\x04text\x18\x06 \x01(\t\x12\x15\n\rtext_position\x18\x07 \x01(\t\x12\x15\n\raspect_ratios\x18\x08 \x03(\t\x12\x0e\n\x06\x66ormat\x18\t \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\n \x01(\t\x12\x11\n\ttimestamp\x18\x0b \x01(\t\"\xbe\x01\n\x12OverlayComposeDone\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x12\n\nvariant_id\x18\x03 \x01(\t\x12\x0e\n\x06locale\x18\x04 \x01(\t\x12\x30\n\x07outputs\x18\x05 \x03(\x0b\x32\x1f.creative_campaign.AspectOutput\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\":\n\x0c\x41spectOutput\x12\x14\n\x0c\x61spect_ratio\x18\x01 \x01(\t\x12\x14\n\x0cs3_uri_final\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'overlay_compose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OVERLAYCOMPOSEREQUEST']._serialized_start=45
  _globals['_OVERLAYCOMPOSEREQUEST']._serialized_end=288
  _globals['_OVERLAYCOMPOSEDONE']._serialized_start=291
  _globals['_OVERLAYCOMPOSEDONE']._serialized_end=481
  _globals['_ASPECTOUTPUT']._serialized_start=483
  _globals['_ASPECTOUTPUT']._serialized_end=541
# @@protoc_insertion_point(module_scope)
